--------------------------------------------------------
--  File created - Sunday-May-04-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFFECTER
--------------------------------------------------------

  CREATE TABLE "MALEK"."AFFECTER" 
   (	"ID_PAT" NUMBER, 
	"ID_LAB" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "MALEK"."EQUIPEMENTS" 
   (	"ID_EQP" NUMBER, 
	"NOM_EQP" VARCHAR2(30 BYTE), 
	"TYPE_EQP" VARCHAR2(30 BYTE), 
	"STATUT_EQP" VARCHAR2(30 BYTE), 
	"DATE_MAINTENANCE_EQP" DATE, 
	"DESCRIPTION_EQP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INJECTIONS
--------------------------------------------------------

  CREATE TABLE "MALEK"."INJECTIONS" 
   (	"ID_PAT" NUMBER, 
	"ID_VAC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVENTIONS
--------------------------------------------------------

  CREATE TABLE "MALEK"."INVENTIONS" 
   (	"ID_MED" NUMBER, 
	"ID_VAC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABORATOIRES
--------------------------------------------------------

  CREATE TABLE "MALEK"."LABORATOIRES" 
   (	"ID_LAB" NUMBER, 
	"NOM_LAB" VARCHAR2(30 BYTE), 
	"LOCALISATION_LAB" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CONTACT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDECINS
--------------------------------------------------------

  CREATE TABLE "MALEK"."MEDECINS" 
   (	"ID_MED" NUMBER, 
	"NOM_MED" VARCHAR2(20 BYTE), 
	"PRENOM_MED" VARCHAR2(20 BYTE), 
	"SPECIALITE_MED" VARCHAR2(25 BYTE), 
	"CONTACT_MED" VARCHAR2(50 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(50 BYTE), 
	"QUESTION" VARCHAR2(50 BYTE), 
	"REPONSE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "MALEK"."PATIENTS" 
   (	"ID_PAT" NUMBER, 
	"NOM_PAT" VARCHAR2(20 BYTE), 
	"PRENOM_PAT" VARCHAR2(20 BYTE), 
	"DATENAIS_PAT" DATE, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"GENRE" VARCHAR2(10 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"GROUPSANGUIN" VARCHAR2(5 BYTE), 
	"CERTIFICAT" BLOB, 
	"TEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CERTIFICAT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RENDEZ_VOUS
--------------------------------------------------------

  CREATE TABLE "MALEK"."RENDEZ_VOUS" 
   (	"ID_RDV" NUMBER, 
	"DATE_RDV" DATE, 
	"HEURE_RDV" TIMESTAMP (6), 
	"PRIORITE_RDV" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ID_PAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATIONS
--------------------------------------------------------

  CREATE TABLE "MALEK"."UTILISATIONS" 
   (	"ID_MED" NUMBER, 
	"ID_EQP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VACCINS
--------------------------------------------------------

  CREATE TABLE "MALEK"."VACCINS" 
   (	"ID_VAC" NUMBER, 
	"NOM_VAC" VARCHAR2(100 BYTE), 
	"TYPE_VAC" VARCHAR2(50 BYTE), 
	"FABRICANT_VAC" VARCHAR2(100 BYTE), 
	"DATE_FABRICATION" DATE, 
	"DATE_EXPIRATION" DATE, 
	"TEMPERATURE_CONSERVATION" NUMBER(5,2), 
	"PAYS_ORIGIN" VARCHAR2(50 BYTE), 
	"STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MALEK.AFFECTER
SET DEFINE OFF;
REM INSERTING into MALEK.EQUIPEMENTS
SET DEFINE OFF;
Insert into MALEK.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (1,'UUU','HHHH','HHHH',to_date('02-MAY-25','DD-MON-RR'),'QQQQQQQ');
REM INSERTING into MALEK.INJECTIONS
SET DEFINE OFF;
REM INSERTING into MALEK.INVENTIONS
SET DEFINE OFF;
REM INSERTING into MALEK.LABORATOIRES
SET DEFINE OFF;
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (100,'DHIAb','Sfax','inactif','12458796');
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (7,'uyiyg','Sousse','Actif','12457865');
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (1,'tbryhy','Matir','Actif','12365412');
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (95,'maram','Tunis','inactif','15984752');
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (4,'issa','Tunis Rue du Caire ','Actif','12365875');
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (6,'ABOGAA ALMEZWED','GAA AL MEZWED','inactif','12365985');
Insert into MALEK.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (2,'DHIA','Sfax','Actif','14587542');
REM INSERTING into MALEK.MEDECINS
SET DEFINE OFF;
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (11,'DHIA','DHIA','Toxicologie','12345678',null,'13051968','Quel est le nom de votre première école ?','sadkeya');
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (13,'DHIA','DHIA','Hématologie','12345678',null,'16',null,null);
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (112,'DHIA','chebbi','Parasitologie','12345678',null,'11022005','Quel est le nom de votre premier animal ?','saaaakr');
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (895,'DHIA','chebbi','Anatomopathologie','98652801',null,null,null,null);
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (39,'DHIA','chebbi','Biochimie','94041035','2005','2005',null,'chat');
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (9,'chahd','bekir','Toxicologie','12345678',null,null,null,null);
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (5,'chahd','bekir','Parasitologie','12345678',null,null,null,null);
Insert into MALEK.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE) values (852,'ghak','DHIA','Immunologie','52634187',null,'azerty','Quel est le nom de votre premier animal ?','chahed');
REM INSERTING into MALEK.PATIENTS
SET DEFINE OFF;
Insert into MALEK.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (63,'amin','ben',to_date('01-JAN-00','DD-MON-RR'),'amin@gmail.com','Mâle','tunis','B-',55548722);
Insert into MALEK.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (31,'malik','ben',to_date('01-OCT-04','DD-MON-RR'),'ddqqccq@gmail.com','Mâle','dqdq','O-',1919);
Insert into MALEK.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (89,'malek','benre',to_date('01-JAN-19','DD-MON-RR'),'malek@gmail.com','Mâle','ezzahra','A+',58414391);
REM INSERTING into MALEK.RENDEZ_VOUS
SET DEFINE OFF;
Insert into MALEK.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (1,to_date('22-MAY-25','DD-MON-RR'),to_timestamp('22-MAY-25 01.37.59.902000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'ihjgjh','vhvg',31);
REM INSERTING into MALEK.UTILISATIONS
SET DEFINE OFF;
REM INSERTING into MALEK.VACCINS
SET DEFINE OFF;
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (14,'dqdq','ARNm','dqdq',to_date('18-APR-25','DD-MON-RR'),to_date('31-MAY-25','DD-MON-RR'),20.5,'qdqdq',10);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (2,'zeaze','ARNm','eazeaz',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),20,'zaeaze',105);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (5,'zeae','ARNm','azea',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),70,'zea',100);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (15,'zzzzz','Proteine Sous-Unite','eeeee',to_date('01-JAN-24','DD-MON-RR'),to_date('09-APR-25','DD-MON-RR'),9,'ggggg',22);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (3,'ali','ARNm','mplop',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),12,'ahla',20);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (4,'zeae','ARNm','azea',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),36,'zea',77);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (6,'ahmed','ARNm','azea',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),36,'zea',55);
Insert into MALEK.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (7,'zedaz','ARNm','eazeae',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),45,'ibiza',30);
--------------------------------------------------------
--  DDL for Index INVENTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."INVENTIONS_PK" ON "MALEK"."INVENTIONS" ("ID_MED", "ID_VAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UTILISATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."UTILISATIONS_PK" ON "MALEK"."UTILISATIONS" ("ID_MED", "ID_EQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABORATOIRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."LABORATOIRES_PK" ON "MALEK"."LABORATOIRES" ("ID_LAB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."EQUIPEMENTS_PK" ON "MALEK"."EQUIPEMENTS" ("ID_EQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."PATIENTS_PK" ON "MALEK"."PATIENTS" ("ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INJECTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."INJECTER_PK" ON "MALEK"."INJECTIONS" ("ID_VAC", "ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RENDEZ_VOUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."RENDEZ_VOUS_PK" ON "MALEK"."RENDEZ_VOUS" ("ID_RDV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AFFECTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."AFFECTER_PK" ON "MALEK"."AFFECTER" ("ID_LAB", "ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VACCINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."VACCINS_PK" ON "MALEK"."VACCINS" ("ID_VAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger LABORATOIRES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."LABORATOIRES_TRG" 
BEFORE INSERT ON LABORATOIRES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "MALEK"."LABORATOIRES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AFFECTER
--------------------------------------------------------

  ALTER TABLE "MALEK"."AFFECTER" ADD CONSTRAINT "AFFECTER_PK" PRIMARY KEY ("ID_LAB", "ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."AFFECTER" MODIFY ("ID_LAB" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."AFFECTER" MODIFY ("ID_PAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABORATOIRES
--------------------------------------------------------

  ALTER TABLE "MALEK"."LABORATOIRES" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."LABORATOIRES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."LABORATOIRES" MODIFY ("LOCALISATION_LAB" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."LABORATOIRES" MODIFY ("NOM_LAB" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."LABORATOIRES" ADD CONSTRAINT "LABORATOIRES_PK" PRIMARY KEY ("ID_LAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."LABORATOIRES" MODIFY ("ID_LAB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDECINS
--------------------------------------------------------

  ALTER TABLE "MALEK"."MEDECINS" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVENTIONS
--------------------------------------------------------

  ALTER TABLE "MALEK"."INVENTIONS" ADD CONSTRAINT "INVENTIONS_PK" PRIMARY KEY ("ID_MED", "ID_VAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."INVENTIONS" MODIFY ("ID_VAC" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."INVENTIONS" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VACCINS
--------------------------------------------------------

  ALTER TABLE "MALEK"."VACCINS" ADD CONSTRAINT "CHK_TYPE_VAC" CHECK (TYPE_VAC IN ('ARNm', 'Virus Inactive', 'Vecteur Viral', 'Proteine Sous-Unite')) ENABLE;
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("ID_VAC" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("NOM_VAC" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("TYPE_VAC" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("FABRICANT_VAC" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("DATE_FABRICATION" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("DATE_EXPIRATION" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("TEMPERATURE_CONSERVATION" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" MODIFY ("PAYS_ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."VACCINS" ADD CONSTRAINT "VACCINS_PK" PRIMARY KEY ("ID_VAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "MALEK"."PATIENTS" ADD CONSTRAINT "PATIENTS_PK" PRIMARY KEY ("ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("GROUPSANGUIN" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("GENRE" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("DATENAIS_PAT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("PRENOM_PAT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("NOM_PAT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("ID_PAT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PATIENTS" MODIFY ("TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "MALEK"."EQUIPEMENTS" MODIFY ("DESCRIPTION_EQP" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."EQUIPEMENTS" MODIFY ("DATE_MAINTENANCE_EQP" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."EQUIPEMENTS" MODIFY ("STATUT_EQP" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."EQUIPEMENTS" MODIFY ("TYPE_EQP" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."EQUIPEMENTS" MODIFY ("NOM_EQP" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("ID_EQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."EQUIPEMENTS" MODIFY ("ID_EQP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATIONS
--------------------------------------------------------

  ALTER TABLE "MALEK"."UTILISATIONS" ADD CONSTRAINT "UTILISATIONS_PK" PRIMARY KEY ("ID_MED", "ID_EQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."UTILISATIONS" MODIFY ("ID_EQP" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."UTILISATIONS" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INJECTIONS
--------------------------------------------------------

  ALTER TABLE "MALEK"."INJECTIONS" ADD CONSTRAINT "INJECTER_PK" PRIMARY KEY ("ID_VAC", "ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."INJECTIONS" MODIFY ("ID_VAC" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."INJECTIONS" MODIFY ("ID_PAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDEZ_VOUS
--------------------------------------------------------

  ALTER TABLE "MALEK"."RENDEZ_VOUS" MODIFY ("ID_PAT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."RENDEZ_VOUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."RENDEZ_VOUS" MODIFY ("PRIORITE_RDV" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."RENDEZ_VOUS" MODIFY ("HEURE_RDV" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."RENDEZ_VOUS" MODIFY ("DATE_RDV" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."RENDEZ_VOUS" ADD CONSTRAINT "RENDEZ_VOUS_PK" PRIMARY KEY ("ID_RDV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."RENDEZ_VOUS" MODIFY ("ID_RDV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AFFECTER
--------------------------------------------------------

  ALTER TABLE "MALEK"."AFFECTER" ADD CONSTRAINT "FK_ALAB" FOREIGN KEY ("ID_LAB")
	  REFERENCES "MALEK"."LABORATOIRES" ("ID_LAB") ENABLE;
  ALTER TABLE "MALEK"."AFFECTER" ADD CONSTRAINT "FK_APAT" FOREIGN KEY ("ID_PAT")
	  REFERENCES "MALEK"."PATIENTS" ("ID_PAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INJECTIONS
--------------------------------------------------------

  ALTER TABLE "MALEK"."INJECTIONS" ADD CONSTRAINT "FK_INJPAT" FOREIGN KEY ("ID_PAT")
	  REFERENCES "MALEK"."PATIENTS" ("ID_PAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENDEZ_VOUS
--------------------------------------------------------

  ALTER TABLE "MALEK"."RENDEZ_VOUS" ADD CONSTRAINT "FK_RVPAT" FOREIGN KEY ("ID_PAT")
	  REFERENCES "MALEK"."PATIENTS" ("ID_PAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATIONS
--------------------------------------------------------

  ALTER TABLE "MALEK"."UTILISATIONS" ADD CONSTRAINT "FK_UEQP" FOREIGN KEY ("ID_EQP")
	  REFERENCES "MALEK"."EQUIPEMENTS" ("ID_EQP") ENABLE;
