--------------------------------------------------------
--  File created - Tuesday-May-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFFECTER
--------------------------------------------------------

  CREATE TABLE "DHIA"."AFFECTER" 
   (	"ID_PAT" NUMBER, 
	"ID_LAB" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "DHIA"."EQUIPEMENTS" 
   (	"ID_EQP" NUMBER, 
	"NOM_EQP" VARCHAR2(30 BYTE), 
	"TYPE_EQP" VARCHAR2(30 BYTE), 
	"STATUT_EQP" VARCHAR2(30 BYTE), 
	"DATE_MAINTENANCE_EQP" DATE, 
	"DESCRIPTION_EQP" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INJECTIONS
--------------------------------------------------------

  CREATE TABLE "DHIA"."INJECTIONS" 
   (	"ID_PAT" NUMBER, 
	"ID_VAC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVENTIONS
--------------------------------------------------------

  CREATE TABLE "DHIA"."INVENTIONS" 
   (	"ID_MED" NUMBER, 
	"ID_VAC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABORATOIRES
--------------------------------------------------------

  CREATE TABLE "DHIA"."LABORATOIRES" 
   (	"ID_LAB" NUMBER, 
	"NOM_LAB" VARCHAR2(30 BYTE), 
	"LOCALISATION_LAB" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CONTACT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDECINS
--------------------------------------------------------

  CREATE TABLE "DHIA"."MEDECINS" 
   (	"ID_MED" NUMBER, 
	"NOM_MED" VARCHAR2(20 BYTE), 
	"PRENOM_MED" VARCHAR2(20 BYTE), 
	"SPECIALITE_MED" VARCHAR2(25 BYTE), 
	"CONTACT_MED" VARCHAR2(50 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(50 BYTE), 
	"QUESTION" VARCHAR2(50 BYTE), 
	"REPONSE" VARCHAR2(50 BYTE), 
	"RFID_UID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "DHIA"."PATIENTS" 
   (	"ID_PAT" NUMBER, 
	"NOM_PAT" VARCHAR2(20 BYTE), 
	"PRENOM_PAT" VARCHAR2(20 BYTE), 
	"DATENAIS_PAT" DATE, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"GENRE" VARCHAR2(10 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"GROUPSANGUIN" VARCHAR2(5 BYTE), 
	"CERTIFICAT" BLOB, 
	"TEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CERTIFICAT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RENDEZ_VOUS
--------------------------------------------------------

  CREATE TABLE "DHIA"."RENDEZ_VOUS" 
   (	"ID_RDV" NUMBER, 
	"DATE_RDV" DATE, 
	"HEURE_RDV" TIMESTAMP (6), 
	"PRIORITE_RDV" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ID_PAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATIONS
--------------------------------------------------------

  CREATE TABLE "DHIA"."UTILISATIONS" 
   (	"ID_MED" NUMBER, 
	"ID_EQP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VACCINS
--------------------------------------------------------

  CREATE TABLE "DHIA"."VACCINS" 
   (	"ID_VAC" NUMBER, 
	"NOM_VAC" VARCHAR2(100 BYTE), 
	"TYPE_VAC" VARCHAR2(50 BYTE), 
	"FABRICANT_VAC" VARCHAR2(100 BYTE), 
	"DATE_FABRICATION" DATE, 
	"DATE_EXPIRATION" DATE, 
	"TEMPERATURE_CONSERVATION" NUMBER(5,2), 
	"PAYS_ORIGIN" VARCHAR2(50 BYTE), 
	"STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DHIA.AFFECTER
SET DEFINE OFF;
REM INSERTING into DHIA.EQUIPEMENTS
SET DEFINE OFF;
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (8,'Hibaa','Outil','Actif',to_date('01-JAN-00','DD-MON-RR'),'qsd');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (1,'Réfrigérateur','Outil','Actif',to_date('01-JAN-00','DD-MON-RR'),'qqsq');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (2,'Réfrigérateur2','Outil','Actif',to_date('01-JAN-00','DD-MON-RR'),'wuj');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (3,'Hiba','Informatique','Actif',to_date('01-JAN-00','DD-MON-RR'),'a');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (4,'Mallek','Machine','Actif',to_date('01-JAN-00','DD-MON-RR'),'hh');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (5,'Maram','Outil','Actif',to_date('01-JAN-00','DD-MON-RR'),'a');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (7,'Tubes','Outil','Actif',to_date('01-JAN-00','DD-MON-RR'),'qq');
Insert into DHIA.EQUIPEMENTS (ID_EQP,NOM_EQP,TYPE_EQP,STATUT_EQP,DATE_MAINTENANCE_EQP,DESCRIPTION_EQP) values (6,'Akrem','Machine','Inactif',to_date('01-JAN-00','DD-MON-RR'),'a');
REM INSERTING into DHIA.INJECTIONS
SET DEFINE OFF;
Insert into DHIA.INJECTIONS (ID_PAT,ID_VAC) values (13,1);
Insert into DHIA.INJECTIONS (ID_PAT,ID_VAC) values (13,2);
Insert into DHIA.INJECTIONS (ID_PAT,ID_VAC) values (13,3);
REM INSERTING into DHIA.INVENTIONS
SET DEFINE OFF;
REM INSERTING into DHIA.LABORATOIRES
SET DEFINE OFF;
Insert into DHIA.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (62,'ABOGAA ALMEZWED','GAA AL MEZWED','Actif','12365985');
Insert into DHIA.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (43,'issa','Tunis Rue du Caire ','Actif','12365875');
Insert into DHIA.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (23,'DCFD','Gafsa','Actif','12345678');
Insert into DHIA.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (95,'maram','Tunis','inactif','15984752');
Insert into DHIA.LABORATOIRES (ID_LAB,NOM_LAB,LOCALISATION_LAB,STATUS,CONTACT) values (233,'aarraa','Tunis','Actif','12345678');
REM INSERTING into DHIA.MEDECINS
SET DEFINE OFF;
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (11,'DHIA','DHIA','Toxicologie','12345678',null,'13051968','Quel est le nom de votre premi?re ?cole ?','sadkeya',null);
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (13,'DHIA','DHIA','H?matologie','12345678',null,'16',null,null,null);
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (112,'DHIA','chebbi','Parasitologie','12345678',null,'11022005','Quel est le nom de votre premier animal ?','saaaakr',null);
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (895,'DHIA','chebbi','Anatomopathologie','98652801',null,null,null,null,null);
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (39,'dejoui','sadekkk','Biochimie','88888888','2005','2005',null,'chat','A36F86F5');
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (9,'chahd','bekir','Toxicologie','12345678',null,null,null,null,null);
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (5,'chahd','bekir','Parasitologie','12345678',null,null,null,null,null);
Insert into DHIA.MEDECINS (ID_MED,NOM_MED,PRENOM_MED,SPECIALITE_MED,CONTACT_MED,LOGIN,MDP,QUESTION,REPONSE,RFID_UID) values (22,'HIBAA','HIBA','Toxicologie','12345678',null,'BHIM','Quel est votre plat préféré ?','CHAT',null);
REM INSERTING into DHIA.PATIENTS
SET DEFINE OFF;
Insert into DHIA.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (1,'dd','dd',to_date('04-MAR-25','DD-MON-RR'),'dd','ddd','dddd','d',94558031);
Insert into DHIA.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (2,'ddd','aaa',to_date('28-MAR-25','DD-MON-RR'),'aa','a','a','a',58091456);
Insert into DHIA.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (3,'bakir','chahd',to_date('04-APR-25','DD-MON-RR'),'a','a','a','a',58414707);
Insert into DHIA.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (12,'a','a',to_date('15-APR-25','DD-MON-RR'),'a','a','a','a',11111111);
Insert into DHIA.PATIENTS (ID_PAT,NOM_PAT,PRENOM_PAT,DATENAIS_PAT,EMAIL,GENRE,ADRESSE,GROUPSANGUIN,TEL) values (13,'a','a',to_date('15-APR-25','DD-MON-RR'),'a','s','s','s',11111111);
REM INSERTING into DHIA.RENDEZ_VOUS
SET DEFINE OFF;
Insert into DHIA.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (1,to_date('06-MAY-25','DD-MON-RR'),to_timestamp('01-MAY-25 01.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Urgente','Programmer',1);
Insert into DHIA.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (3,to_date('12-MAY-25','DD-MON-RR'),to_timestamp('01-MAY-25 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Normal','Programmer',1);
Insert into DHIA.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (4,to_date('06-MAY-25','DD-MON-RR'),to_timestamp('01-MAY-25 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Urgente','Programmer',1);
Insert into DHIA.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (6,to_date('06-JUN-25','DD-MON-RR'),to_timestamp('01-MAY-25 01.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Urgente','Programmer',1);
Insert into DHIA.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (2,to_date('06-DEC-25','DD-MON-RR'),to_timestamp('01-MAY-25 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Normal','Programmer',1);
Insert into DHIA.RENDEZ_VOUS (ID_RDV,DATE_RDV,HEURE_RDV,PRIORITE_RDV,STATUS,ID_PAT) values (9,to_date('16-MAY-25','DD-MON-RR'),to_timestamp('01-MAY-25 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Moyenne','Programmer',1);
REM INSERTING into DHIA.UTILISATIONS
SET DEFINE OFF;
REM INSERTING into DHIA.VACCINS
SET DEFINE OFF;
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (1,'karray777','ARNm','habbouba',to_date('12-MAR-25','DD-MON-RR'),to_date('27-MAR-25','DD-MON-RR'),30,'sfax',200);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (2,'zeaze','ARNm','eazeaz',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),20,'zaeaze',105);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (5,'zeae','ARNm','azea',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),70,'zea',100);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (15,'zzzzz','Proteine Sous-Unite','eeeee',to_date('01-JAN-24','DD-MON-RR'),to_date('09-APR-25','DD-MON-RR'),9,'ggggg',22);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (3,'ali','ARNm','mplop',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),12,'ahla',20);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (4,'zeae','ARNm','azea',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),36,'zea',77);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (6,'ahmed','ARNm','azea',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),36,'zea',55);
Insert into DHIA.VACCINS (ID_VAC,NOM_VAC,TYPE_VAC,FABRICANT_VAC,DATE_FABRICATION,DATE_EXPIRATION,TEMPERATURE_CONSERVATION,PAYS_ORIGIN,STOCK) values (7,'zedaz','Vecteur Viral','eazeae',to_date('01-JAN-24','DD-MON-RR'),to_date('13-MAR-25','DD-MON-RR'),45,'ibiza',30);
--------------------------------------------------------
--  DDL for Index AFFECTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."AFFECTER_PK" ON "DHIA"."AFFECTER" ("ID_LAB", "ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."CK1" ON "DHIA"."EQUIPEMENTS" ("NOM_EQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."EQUIPEMENTS_PK" ON "DHIA"."EQUIPEMENTS" ("ID_EQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INJECTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."INJECTER_PK" ON "DHIA"."INJECTIONS" ("ID_VAC", "ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INVENTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."INVENTIONS_PK" ON "DHIA"."INVENTIONS" ("ID_MED", "ID_VAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABORATOIRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."LABORATOIRES_PK" ON "DHIA"."LABORATOIRES" ("ID_LAB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."PATIENTS_PK" ON "DHIA"."PATIENTS" ("ID_PAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RENDEZ_VOUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."RENDEZ_VOUS_PK" ON "DHIA"."RENDEZ_VOUS" ("ID_RDV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UTILISATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."UTILISATIONS_PK" ON "DHIA"."UTILISATIONS" ("ID_MED", "ID_EQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VACCINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DHIA"."VACCINS_PK" ON "DHIA"."VACCINS" ("ID_VAC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger LABORATOIRES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DHIA"."LABORATOIRES_TRG" 
BEFORE INSERT ON LABORATOIRES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "DHIA"."LABORATOIRES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AFFECTER
--------------------------------------------------------

  ALTER TABLE "DHIA"."AFFECTER" ADD CONSTRAINT "AFFECTER_PK" PRIMARY KEY ("ID_LAB", "ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."AFFECTER" MODIFY ("ID_LAB" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."AFFECTER" MODIFY ("ID_PAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "DHIA"."EQUIPEMENTS" MODIFY ("ID_EQP" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("ID_EQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."EQUIPEMENTS" MODIFY ("NOM_EQP" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EQUIPEMENTS" MODIFY ("TYPE_EQP" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EQUIPEMENTS" MODIFY ("STATUT_EQP" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."EQUIPEMENTS" MODIFY ("DATE_MAINTENANCE_EQP" NOT NULL DISABLE);
  ALTER TABLE "DHIA"."EQUIPEMENTS" ADD CONSTRAINT "CK1" UNIQUE ("NOM_EQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INJECTIONS
--------------------------------------------------------

  ALTER TABLE "DHIA"."INJECTIONS" ADD CONSTRAINT "INJECTER_PK" PRIMARY KEY ("ID_VAC", "ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."INJECTIONS" MODIFY ("ID_VAC" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."INJECTIONS" MODIFY ("ID_PAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVENTIONS
--------------------------------------------------------

  ALTER TABLE "DHIA"."INVENTIONS" ADD CONSTRAINT "INVENTIONS_PK" PRIMARY KEY ("ID_MED", "ID_VAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."INVENTIONS" MODIFY ("ID_VAC" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."INVENTIONS" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABORATOIRES
--------------------------------------------------------

  ALTER TABLE "DHIA"."LABORATOIRES" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."LABORATOIRES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."LABORATOIRES" MODIFY ("LOCALISATION_LAB" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."LABORATOIRES" MODIFY ("NOM_LAB" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."LABORATOIRES" ADD CONSTRAINT "LABORATOIRES_PK" PRIMARY KEY ("ID_LAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."LABORATOIRES" MODIFY ("ID_LAB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDECINS
--------------------------------------------------------

  ALTER TABLE "DHIA"."MEDECINS" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "DHIA"."PATIENTS" ADD CONSTRAINT "PATIENTS_PK" PRIMARY KEY ("ID_PAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("GROUPSANGUIN" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("GENRE" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("DATENAIS_PAT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("PRENOM_PAT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("NOM_PAT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("ID_PAT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."PATIENTS" MODIFY ("TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDEZ_VOUS
--------------------------------------------------------

  ALTER TABLE "DHIA"."RENDEZ_VOUS" MODIFY ("ID_PAT" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RENDEZ_VOUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RENDEZ_VOUS" MODIFY ("PRIORITE_RDV" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RENDEZ_VOUS" MODIFY ("HEURE_RDV" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RENDEZ_VOUS" MODIFY ("DATE_RDV" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."RENDEZ_VOUS" ADD CONSTRAINT "RENDEZ_VOUS_PK" PRIMARY KEY ("ID_RDV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."RENDEZ_VOUS" MODIFY ("ID_RDV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATIONS
--------------------------------------------------------

  ALTER TABLE "DHIA"."UTILISATIONS" ADD CONSTRAINT "UTILISATIONS_PK" PRIMARY KEY ("ID_MED", "ID_EQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DHIA"."UTILISATIONS" MODIFY ("ID_EQP" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."UTILISATIONS" MODIFY ("ID_MED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VACCINS
--------------------------------------------------------

  ALTER TABLE "DHIA"."VACCINS" ADD CONSTRAINT "CHK_TYPE_VAC" CHECK (TYPE_VAC IN ('ARNm', 'Virus Inactive', 'Vecteur Viral', 'Proteine Sous-Unite')) ENABLE;
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("ID_VAC" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("NOM_VAC" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("TYPE_VAC" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("FABRICANT_VAC" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("DATE_FABRICATION" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("DATE_EXPIRATION" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("TEMPERATURE_CONSERVATION" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" MODIFY ("PAYS_ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "DHIA"."VACCINS" ADD CONSTRAINT "VACCINS_PK" PRIMARY KEY ("ID_VAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFFECTER
--------------------------------------------------------

  ALTER TABLE "DHIA"."AFFECTER" ADD CONSTRAINT "FK_ALAB" FOREIGN KEY ("ID_LAB")
	  REFERENCES "DHIA"."LABORATOIRES" ("ID_LAB") ENABLE;
  ALTER TABLE "DHIA"."AFFECTER" ADD CONSTRAINT "FK_APAT" FOREIGN KEY ("ID_PAT")
	  REFERENCES "DHIA"."PATIENTS" ("ID_PAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INJECTIONS
--------------------------------------------------------

  ALTER TABLE "DHIA"."INJECTIONS" ADD CONSTRAINT "FK_INJPAT" FOREIGN KEY ("ID_PAT")
	  REFERENCES "DHIA"."PATIENTS" ("ID_PAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENDEZ_VOUS
--------------------------------------------------------

  ALTER TABLE "DHIA"."RENDEZ_VOUS" ADD CONSTRAINT "FK_RVPAT" FOREIGN KEY ("ID_PAT")
	  REFERENCES "DHIA"."PATIENTS" ("ID_PAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATIONS
--------------------------------------------------------

  ALTER TABLE "DHIA"."UTILISATIONS" ADD CONSTRAINT "FK_UEQP" FOREIGN KEY ("ID_EQP")
	  REFERENCES "DHIA"."EQUIPEMENTS" ("ID_EQP") ENABLE;
